Error screen
develhope/android5_team1_forecastapp pull request #7
Opened 2023-05-31 10:05 UTC by Damidjo

An error screen appears when the network fails to connect.

2023-06-07 07:20 UTC, ShAdOwNeT88 requested changes

2023-06-07 07:20 UTC, ShAdOwNeT88 commented on app/src/main/res/layout/error_screen.xml
> +        android:layout_marginTop="150dp"
I don't think that we need to have all those dimensions hardcoded, please export them into dimens file

2023-06-07 07:20 UTC, ShAdOwNeT88 commented on app/src/main/res/values/strings.xml
> +        Verifica la tua rete e riprova.
It's unnecessary to paste strings with new line like this, they will be not rendered into the ui.

2023-06-07 07:20 UTC, ShAdOwNeT88 commented on app/src/main/res/values/strings.xml
> +    <string name="riprova">Riprova</string>
Why we are mixing Eng and It?

2023-06-12 12:31 UTC, Damidjo commented
Added dimen.xml with dimension of error-screen.
Solved language issues
Solved string issues

2023-06-13 14:56 UTC, ShAdOwNeT88 requested changes

2023-06-13 14:56 UTC, ShAdOwNeT88 commented on app/src/main/res/values/dimen.xml
> +</resources>
If we have three dimensions at 20dp, why do we merge them into one single dimension named `margin_20`

2023-06-13 14:56 UTC, ShAdOwNeT88 commented on app/src/main/res/values/strings.xml
>  </resources>
Maybe we need to have the en strings too?

2023-06-14 09:13 UTC, merged